#!/bin/bash
if test ! -f $2
then 
	echo "die Datei existiert nicht!"
	exit 1
fi

if test $# -ne 2
then
	exit 2
	echo "Zu viele oder zu wenige Parameter angegeben!"
fi

if test "$1" = " "
then 
	exit 3
fi

grep -o "$1" $2 | wc -w

exit 0
